version: '3.8'
services:
  app:
    build: .
    volumes:
      - . :/myorderbook
    ports:
      - "8000:8000"
    image: app:myorderbook
    container_name: myorderbook_container
    command: python manage.py runserver 0.0.0.0:8000